# backend/app/agents/cot_rag_agent.py

import logging
import json
import re
from typing import Dict, List, Any
from dataclasses import dataclass

from app.db.llm_interface import LLMInterface
from app.db.vector_store import VectorStore
from app.db.graph_db import Neo4jGraphDB
from app.core.settings_manager import settings_manager

@dataclass
class CoTStep:
    step_number: int
    reasoning: str
    conclusion: str
    confidence: float

class ChainOfThoughtRAGAgent:
    def __init__(self, llm_interface: LLMInterface, vector_store: VectorStore, graph_db: Neo4jGraphDB, logger: logging.Logger):
        self.llm_interface = llm_interface
        self.vector_store = vector_store
        self.graph_db = graph_db
        self.logger = logger

    def _classify_intent(self, query: str) -> str:
        prompt = f"""
        Classify this student query about C programming:
        
        1. REVIEW: The user has provided C code. Look for:
           - Semicolons at end of lines (;)
           - Brackets {{ }} or parentheses ()
           - C keywords (int, float, void, return, printf)
           - Or asking "Is this right?"
        2. CONCEPT: Asking "what is...", "explain...", "definition of...", "how does X work?"
        3. PROBLEM: Asking "how to...", "write a code...", "solve..."
        4. DEBUG: Asking "why is this error...", "fix this..."

        Query: "{query}"
        
        Respond with ONE word: CONCEPT, PROBLEM, DEBUG, or REVIEW.
        """
        return self.llm_interface.generate_response(prompt).strip().upper()

    def _sanitize_mermaid(self, text: str) -> str:
        """
        Fixes common Mermaid syntax errors generated by LLMs.
        Removes parentheses () inside node labels [ ].
        """
        def replace_parens(match):
            # match.group(0) is the whole node e.g. [Function(args)]
            # We replace ( with space and ) with nothing inside the brackets
            content = match.group(1)
            clean_content = content.replace("(", " ").replace(")", "")
            return f"[{clean_content}]"

        # Regex to find node labels: [Any text]
        # We assume standard nodes [ ] or { } or ( )
        # This is a simple heuristic cleanup
        cleaned = re.sub(r'\[(.*?)\]', replace_parens, text)
        cleaned = re.sub(r'\{(.*?)\}', replace_parens, text)
        return cleaned

    def _expand_query_using_graph(self, query: str, initial_entities: List[str]) -> List[str]:
        expanded_terms = []
        for entity in initial_entities:
            cypher = """
            MATCH (req)-[:IS_PREREQUISITE_FOR]->(target {name: $name})
            RETURN req.name as name
            UNION
            MATCH (target {name: $name})-[:REQUIRES_UNDERSTANDING_OF]->(req)
            RETURN req.name as name
            """
            results = self.graph_db.execute_query(cypher, {"name": entity})
            for record in results:
                expanded_terms.append(record['name'])
        return list(set(expanded_terms))

    def _execute_retrieval(self, query: str, intent: str, user_role: str = 'student') -> List[Dict[str, Any]]:
        """
        Retrieves documents with Graph expansion, Vector search, and Strict Filtering (Gatekeeper).
        """
        # 1. Extract keywords
        extract_prompt = f"Extract the main C programming terms from: '{query}'. Return as comma-separated list."
        entities_str = self.llm_interface.generate_response(extract_prompt)
        entities = [e.strip() for e in entities_str.split(',') if e.strip()]
        
        self.logger.info(f"Extracted Entities: {entities}")

        # 2. Graph Expansion
        related_terms = self._expand_query_using_graph(query, entities)
        self.logger.info(f"Graph suggested related terms: {related_terms}")

        # 3. Vector Search
        query_embedding = self.llm_interface.get_embedding(query)
        # We fetch more candidates (top_k=8) because the Gatekeeper might filter some out
        raw_chunks = self.vector_store.query(query_embedding, top_k=8)

        # 4. Graph Related Search (Optional expansion)
        if related_terms:
            expanded_query = " ".join(related_terms)
            expanded_embedding = self.llm_interface.get_embedding(expanded_query)
            related_chunks = self.vector_store.query(expanded_embedding, top_k=3)
            raw_chunks.extend(related_chunks)

        # --- GATEKEEPER LOGIC (Filtering) ---
        valid_chunks = []
        # Load the current visibility settings from the dashboard manager
        topic_settings = settings_manager.get_settings()
        
        # Strictness level for vector match (0.0 to 1.0)
        # Higher = stricter (fewer hallucinations), Lower = more lenient
        SCORE_THRESHOLD = 0.28 

        seen_ids = set()

        for chunk in raw_chunks:
            # Deduplicate based on chunk ID
            chunk_id = chunk.get('metadata', {}).get('chunk_id')
            if chunk_id in seen_ids:
                continue
            seen_ids.add(chunk_id)

            meta = chunk.get('metadata', {})
            
            # CHECK A: Relevance Score
            # If the vector database says this match is weak, ignore it.
            if chunk.get('score', 0) <= SCORE_THRESHOLD:
                continue

            # CHECK B: Access Level (Teacher vs Student)
            # If the user is a 'student', they cannot see documents marked 'teacher'
            chunk_access = meta.get('access_level', 'student')
            if user_role == 'student' and chunk_access == 'teacher':
                self.logger.info(f"⛔ Access Denied: Student tried to access '{meta.get('document_name')}'")
                continue

            # CHECK C: Topic Visibility (Dashboard Toggle)
            # If the teacher turned off this topic in the dashboard, hide it.
            topic = meta.get('topic', 'General')
            # If topic is not in settings, default to True (Visible)
            is_visible = topic_settings.get(topic, True)
            
            if not is_visible:
                self.logger.info(f"🙈 Hidden Content: Topic '{topic}' is currently disabled.")
                continue

            # If it passes all checks, add it
            valid_chunks.append(chunk)
        
        if not valid_chunks:
            self.logger.warning(f"No relevant documents found after filtering (Role: {user_role}).")
            return []
            
        return valid_chunks

    def _generate_suggestions(self, query: str, answer: str, context: str) -> List[str]:
        prompt = f"""
        Based on the student's query and your answer, generate 3 short follow-up options.
        
        Query: "{query}"
        Answer: "{answer}"
        Reference Material: "{context}"
        
        **RULES:**
        1. **STRICT GROUNDING:** Do NOT suggest concepts unless they appear in the Reference Material.
        2. **Option 1 (Curiosity):** A relevant follow-up question.
        3. **Option 2 (Next Step):** The logical next step.
        4. **Option 3 (Challenge):** A specific "Mini-Challenge". Start with "Challenge: ".

        **OUTPUT:** Return ONLY a JSON list of 3 strings.
        """
        response = self.llm_interface.generate_response(prompt)
        try:
            cleaned = response.replace("```json", "").replace("```", "").strip()
            import json
            return json.loads(cleaned)
        except:
            return ["Tell me more", "Show an example", "Challenge: Try writing the code"]

    def _generate_code_review(self, query: str, context: str) -> str:
        prompt = f"""
        You are a supportive C Code Reviewer.
        
        Student's Input: {query}
        Reference Material: {context}

        **RULES:**
        1. **CHECK CONTEXT:** Look for a "[CONTEXT: ...]" tag.
        2. **SANDWICH METHOD:** Positive -> Improvement -> Hint.
        3. **SOURCE GROUNDING:** Use variable names from Reference Material.
        4. **NO SOLUTIONS:** Do not rewrite code.
        
        Format:
        ## Code Review
        **✅ What looks good:** ...
        **⚠️ What needs work:** ...
        **💡 Hint:** ...
        """
        return self.llm_interface.generate_response(prompt)

    def _generate_socratic_plan(self, query: str, context: str) -> str:
        prompt = f"""
        You are an encouraging C Programming Tutor.
        
        Student Query: "{query}"
        Reference Material: {context}

        **CRITICAL RULES:**
        1. **CONCEPT LIMITATION:** You may ONLY teach concepts present in the Reference Material.
           - If the answer is NOT in the Reference Material, state that you do not have information on it.
        2. **SOURCE GROUNDING:** Mention specific files/examples.
        3. **TEXT FIRST:** Text explanation MUST come before any diagrams.
        4. **VISUALIZATION:** If appropriate, include a Mermaid diagram.
           - The code block must ONLY contain the `graph TD` definition.
           - **SANITIZATION:** 
             - ABSOLUTELY NO PARENTHESES `()` inside node labels. 
             - BAD: `A[sum(a,b)]`
             - GOOD: `A[sum a b]` or `A[sum arguments]`
             - Replace `()` with `[]` or spaces if needed.

        Format:
        
        ## Strategy
        [Text Explanation]

        ## Visual Logic
        ```mermaid
        graph TD
           A[Start] --> B[End]
        ```
        
        ## Implementation Plan
        1. **[Step Name]**: ...
        
        ## Guiding Question
        ...
        """
        return self.llm_interface.generate_response(prompt)
    
    def _generate_concept_explanation(self, query: str, context: str) -> str:
        prompt = f"""
        You are an expert C Programming Tutor.
        
        Student Query: "{query}"
        Reference Material: {context}

        **MANDATORY RULES:**
        1. **STRICT LIMITATION:** Check the Reference Material. If the concept (e.g., 'switch', 'crypto') is NOT present, you MUST say:
           "I don't have information about [Concept] in my current reference library." 
           Do NOT explain it using outside knowledge.
        2. **TEXT PRIORITY:** clear text explanation FIRST (min 3 sentences).
        3. **VISUALIZATION:** Generate a Mermaid.js diagram (`graph TD`) if the concept involves flow/structure.
           - **SANITIZATION:** No parentheses `()` or double quotes `"` inside node labels. Use brackets `[]` or single quotes.
        4. **SOURCE GROUNDING:** Quote specific examples from text.

        **STRICT RESPONSE FORMAT:**
        
        ## Explanation
        [Text explanation]

        ## Visual Model
        ```mermaid
        graph TD
           A[Start] --> B{{Condition?}}
           B -- Yes --> C[Action]
           B -- No --> D[End]
        ```
        
        ## Example from Class
        [Reference specific code]
        """
        return self.llm_interface.generate_response(prompt)

    def run(self, query: str, user_role: str = 'student', **kwargs) -> Dict[str, Any]:
        self.logger.info(f"Processing Query: {query}")
        
        intent = self._classify_intent(query)
        self.logger.info(f"Intent Classified: {intent}")
        
        retrieved_chunks = self._execute_retrieval(query, intent, user_role) 
        
        # --- FIX: STRICT HALLUCINATION PREVENTION ---
        # If retrieval yielded 0 results (or all were filtered by low score)
        if not retrieved_chunks:
            return {
                "answer": f"I'm sorry, but I don't have any information about '{query}' in my current reference library. I can only teach you based on the materials provided in this course (Variables, Loops, Arrays, Functions).",
                "sources": [],
                "intent": intent,
                "suggestions": ["Ask about Arrays", "Ask about Loops", "Ask about Variables"],
                "cot_analysis": None,
                "reasoning_quality": 0.0 
            }
        # --------------------------------------------
        
        context_text = ""
        for c in retrieved_chunks:
            source = c.get('metadata', {}).get('document_name', 'Unknown')
            text = c.get('text', '')
            context_text += f"--- Source: {source} ---\n{text}\n\n"
        
        if intent == "REVIEW":
            final_answer = self._generate_code_review(query, context_text)
        elif intent == "PROBLEM" or intent == "DEBUG":
            final_answer = self._generate_socratic_plan(query, context_text)
        else:
            final_answer = self._generate_concept_explanation(query, context_text)

        suggestions = self._generate_suggestions(query, final_answer, context_text)

        formatted_sources = []
        for c in retrieved_chunks:
            source_data = c.get('metadata', {}).copy()
            source_data['chunk_text'] = c.get('text') or c.get('chunk_text') or 'Text missing'
            formatted_sources.append(source_data)

        final_answer = self._sanitize_mermaid(final_answer)
        return {
            "answer": final_answer,
            "sources": formatted_sources,
            "intent": intent,
            "suggestions": suggestions,
            "cot_analysis": None,
            "reasoning_quality": 1.0 
        }